# Generated by Django 5.0.5 on 2025-05-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("easypaisa", "EasyPaisa"),
                            ("jazzcash", "JazzCash"),
                            ("cod", "Cash on Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "delivery_time",
                    models.CharField(
                        choices=[("morning", "Morning"), ("evening", "Evening")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
